# Generated by Django 5.2.4 on 2026-03-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecooo', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('dona', 'dona'), ('kg', 'kg')], default='dona', max_length=10),
        ),
    ]
