# Generated by Django 5.2.4 on 2026-03-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecooo', '0006_alter_product_barcode_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
